apiVersion: v1
kind: Service
metadata:
  name: exposed-internal-cluster
  namespace: openvpn
  labels:
    app: openvpn
    service: openvpn
spec:
  ports:
    - name: internal
      port: 443
      targetPort: 443
  selector:
    app: openvpn
    service: openvpn
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  type: LoadBalancer

