---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openvpn
  namespace: openvpn
  labels:
    component: openvpn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openvpn
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openvpn
  labels:
    component: openvpn
subjects:
  - kind: ServiceAccount
    namespace: openvpn
    name: openvpn
roleRef:
  kind: Role
  name: openvpn
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn
  namespace: openvpn
  labels:
    app: openvpn
    service: openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvpn
      service: openvpn
  template:
    metadata:
      labels:
        app: openvpn
        service: openvpn
    spec:
      serviceAccountName: openvpn
      securityContext:
        runAsUser: 0
      containers:
      - image: quay.io/jmontleon/openvpn:latest
        name: socat
        command:
        - socat
        - TCP-LISTEN:443,fork,reuseaddr
        - TCP:172.30.0.1:443
      - image: quay.io/jmontleon/openvpn:latest
        command:
        - openvpn
        - --config
        - /openvpn.conf
        name: openvpn
        securityContext:
          privileged: true
        volumeMounts:
          - name: openvpn-conf
            mountPath: /openvpn.conf
            subPath: openvpn.conf
      volumes:
      - name: openvpn-conf
        secret:
          secretName: openvpn
          defaultMode: 0400
